"""Shared contracts and constants for CSI Smart Tech FSE 01."""

# Event Types
TYPE_COUNT = "COUNT"
TYPE_VOID = "VOID"
EVENT_TYPES = [TYPE_COUNT, TYPE_VOID]

# Event Processing Statuses
STATUS_ACCEPTED = "ACCEPTED"
STATUS_DUPLICATE = "DUPLICATE"
STATUS_CONFLICT = "CONFLICT"
STATUS_PENDING_REFERENCE = "PENDING_REFERENCE"
STATUS_REJECTED = "REJECTED"
STATUS_RESOLVED = "RESOLVED"

# Acknowledgement Statuses
ACK_STATUS_ACKED = "ACKED"
ACK_STATUS_ALREADY_ACKED = "ALREADY_ACKED"
ACK_STATUS_NOT_READY = "NOT_READY"
ACK_STATUS_NOT_FOUND = "NOT_FOUND"

# State Query Views
VIEW_SUMMARY = "summary"
VIEW_PENDING = "pending"
VIEW_EXCEPTIONS = "exceptions"
ALLOWED_VIEWS = [VIEW_SUMMARY, VIEW_PENDING, VIEW_EXCEPTIONS]

# MQTT Statuses & Commands
MQTT_COMMAND_PROCESS_EVENTS = "PROCESS_EVENTS"
MQTT_STATUS_COMPLETED = "COMPLETED"
MQTT_STATUS_FAILED = "FAILED"
MQTT_STATUS_ONLINE = "ONLINE"
MQTT_STATUS_OFFLINE = "OFFLINE"
MQTT_STATUS_HEARTBEAT = "HEARTBEAT"

# MQTT Error Codes
ERROR_VALIDATION_ERROR = "VALIDATION_ERROR"
ERROR_CANDIDATE_MISMATCH = "CANDIDATE_MISMATCH"
ERROR_UNSUPPORTED_PROTOCOL = "UNSUPPORTED_PROTOCOL"
ERROR_CHALLENGE_EXPIRED = "CHALLENGE_EXPIRED"
ERROR_CHALLENGE_CONFLICT = "CHALLENGE_CONFLICT"
ERROR_INTERNAL_ERROR = "INTERNAL_ERROR"
