# Generated by Django 6.1.2 on 2026-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttChallenge',
            fields=[
                ('challenge_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('protocol_version', models.CharField(default='1.0', max_length=32)),
                ('candidate_id', models.CharField(max_length=64)),
                ('command', models.CharField(default='PROCESS_EVENTS', max_length=64)),
                ('request_body', models.JSONField(default=dict)),
                ('request_hash', models.CharField(db_index=True, max_length=64)),
                ('response_payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='COMPLETED', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mqtt_challenges',
            },
        ),
        migrations.CreateModel(
            name='ProductionSource',
            fields=[
                ('source_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Production Source',
                'verbose_name_plural': 'Production Sources',
                'db_table': 'production_sources',
            },
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=128)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('type', models.CharField(choices=[('COUNT', 'Count'), ('VOID', 'Void')], db_index=True, max_length=16)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('target_event_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('event_time', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('PENDING_REFERENCE', 'Pending Reference'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], db_index=True, default='ACCEPTED', max_length=32)),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_by_event_id', models.CharField(blank=True, max_length=128, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, default='', max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_payload_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'db_table': 'production_events',
                'indexes': [models.Index(fields=['source_id', 'status'], name='production__source__7f3ffe_idx'), models.Index(fields=['type', 'status'], name='production__type_7100cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_id', 'event_id'), name='unique_source_event')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('classification', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DUPLICATE', 'Duplicate'), ('CONFLICT', 'Conflict'), ('PENDING_REFERENCE', 'Pending Reference'), ('REJECTED', 'Rejected')], db_index=True, max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_attempts',
                'indexes': [models.Index(fields=['source_id', 'classification'], name='submission__source__694269_idx'), models.Index(fields=['received_at'], name='submission__receive_63470a_idx')],
            },
        ),
    ]
